#DevProperties

#DBProperties
sping:
  datasource:
    driver-class-name:com.mysql.jdbc.Driver
    url:mysql://localhost:3306/ychdb?userUnicode=true&characterEncoding=utf-8
    username:root
    password:root

#Port
server:
  port: 8080

#mybatis
mybatis:
  mapper-locations: classpath:mapper


