#DevProperties

#DBProperties
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ychdb?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: root

#Port
server:
  port: 8080

#mybatis
mybatis:
  type-aliases-package: com.ych.epcc.entity
  mapper-locations: classpath:/mapper/*.xml




