#DevProperties

#DBProperties
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ychdb?useUnicode=true&characterEncoding=UTF-8&useSSL=false&&allowPublicKeyRetrieval=true
    username: root
    password: 123456



  thymeleaf:
    prefix:
      classpath: /templates
      cache: false
      suffix: .html
      encoding: UTF-8

  mvc:
    static-path-pattern: /static/**
    resources:
      chain:
        strategy:
          content:
            enable: true
            path: /**
  logging:
    level:
      root=debug:


  redis:
    database: 0
    host: localhost
    port: 6379
    password:
    jedis:
      pool:
        max-active: 200
        max-wait: -1
        max-idle: 10
        min-idle: 0
    timeout: 1000

#Port
server:
  port: 8080

#mybatis
mybatis:
  type-aliases-package: com.ych.epcc.entity
  mapper-locations: classpath:/mapper/*.xml

#




